version: '3.8'

services:
  apache-php:
    image: apache-mysqli
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - C:/Users/matha/OneDrive/Desktop/docker-project/app:/var/www/html
    ports:
      - "80:80"
    networks:
      - app-network

  mysql:
    image: mysql
    volumes:
      - C:/Users/matha/OneDrive/Desktop/docker-project/DB:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pw
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge